name: pokedex
description: Flutter Pokédex, você pode pesquisar e navegar por uma extensa lista de Pokémon, desde os clássicos até os mais recentes. Cada Pokémon tem sua própria página dedicada, onde você pode encontrar uma variedade de informações essenciais, incluindo tipo, habilidades, estatísticas de batalha, evoluções e muito mais.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  get_it: ^8.0.0
  go_router: ^14.2.7
  flutter_mobx: ^2.2.1+1
  mobx: ^2.3.3+2
  dio: ^5.1.2
  flutter_svg: ^2.0.5
  equatable: ^2.0.5
  lottie: ^2.3.2

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^0.3.0
  network_image_mock: ^2.1.1
  integration_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/icons/
    - assets/json/

  fonts:
     - family: Poppins
       fonts:
         - asset: assets/fonts/poppins.ttf